name: checklinks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check links on site
      uses: peaceiris/actions-muffet@v0.5.3
      with: 
        args: "--exclude .*linkedin.com/in/mattorb --exclude .*twitter.com/share.* https://mattorb.com"
