name: checklinks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check links on site
      uses: mattorb/actions-muffet@v1.3.1
      with: 
        args: >
          --timeout 20 
          --exclude .*linkedin.com/in/mattorb 
          --exclude .*twitter.com/share.* 
          --exclude "https://graphql.org/learn/pagination/#complete-connection-model"
          https://mattorb.com
