name: Broken links

on: 
  push:
    branches:
    - master
  schedule:
    - cron:  '0 13 * * 6'
  repository_dispatch:
  workflow_dispatch:
jobs:
  serialize:
    runs-on: ubuntu-latest
    steps:
    - name: Give other site assessments time to finish.  need to find a better way.
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check links on site
      uses: mattorb/actions-muffet@v2.4.2-b
      with: 
        args: >
          --timeout 25
          --buffer-size 8192
          --concurrency 10
          --ignore-fragments
          --exclude .*linkedin.com/in/mattorb 
          --exclude .*twitter.com/share.* 
          --exclude "https://www.pmi.org/learning/library/characterizing-unknown-unknowns-6077"
          --exclude "https://github.com/mattorb/blog/actions\?workflow=checklinks"
          --exclude .*crontab.guru/.*
          https://mattorb.com
