name: Broken links

on: 
  push:
    branches:
    - master
  schedule:
    - cron:  '0 13 * * 6'
  repository_dispatch:
  workflow_dispatch:
jobs:
  serialize:
    runs-on: ubuntu-latest
    steps:
    - name: Give other site assessments time to finish.  need to find a better way.
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check links on site
      uses: mattorb/actions-muffet@v2.10.8
      with: 
        args: >
          --timeout 25
          --buffer-size 32768
          --max-connections 10
          --max-connections-per-host 10
          --ignore-fragments
          --header="User-Agent:Mozilla/5.0" 
          --header="Accept-Encoding:zstd,br,gzip,deflate"
          --exclude .*linkedin.com/in/mattorb 
          --exclude .*twitter.com/share.* 
          --exclude "https://www.pmi.org/learning/library/characterizing-unknown-unknowns-6077"
          --exclude "https://github.com/mattorb/blog/actions\?workflow=checklinks"
          --exclude .*crontab.guru/.*
          --exclude '.*twitter.com.*' 
          --exclude 'https://mattorb.com/webmentions/receive/' 
          https://mattorb.com
