name: Test site for publicly known js vulnerabilities

on: 
  push:
    branches:
    - master
  schedule:
    - cron:  '0 13 * * 6'
  repository_dispatch:
jobs:
  serialize:
    runs-on: ubuntu-latest
    steps:
    - name: Give other site assessments time to finish.  need to find a better way.
      uses: jakejarvis/wait-action@master
      with:
        time: '120s'
    - name: Give other site assessments time to finish.  need to find a better way.
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Testing for public javascript library vulnerabilities 
        uses: mattorb/is-website-vulnerable@github-action_v1
        with:
          scan-url: "https://mattorb.com"
