name: JS library CVE's

on: 
  push:
    branches:
    - master
  schedule:
    - cron:  '0 13 * * 6'
  repository_dispatch:
  workflow_dispatch:
jobs:
  serialize:
    runs-on: ubuntu-latest
    steps:
    - name: Give other site assessments time to finish.  need to find a better way.
      uses: jakejarvis/wait-action@master
      with:
        time: '400s'
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Testing for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@master
        with:
          scan-url: "https://mattorb.com"
