name: Lighthoues audit live site
on: 
  push:
    branches:
    - master
  schedule:
    - cron:  '0 13 * * 6'
  repository_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Give other site assessments time to finish.  Need to find a better way.
      uses: jakejarvis/wait-action@master
      with:
        time: '180s'
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://mattorb.com/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'