name: PageSpeed

on: 
  push:
    branches:
    - master
  schedule:
    - cron:  '0 13 * * 6'
  repository_dispatch:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Give other site assessments time to finish.  need to find a better way.
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'
      - name: Running Page Speed Insights, Mobile, Homepage
        uses: mattorb/psi-action@v1
        id: psi_mobile_homepage
        with:
          url: "https://mattorb.com"
          threshold: 72
          strategy: mobile
      - name: Running Page Speed Insights, Desktop, Homepage
        uses: mattorb/psi-action@v1
        id: psi_desktop_homepage
        with:
          url: "https://mattorb.com"
          threshold: 91
          strategy: desktop
      - name: Running Page Speed Insights, Mobile, a typical post page
        uses: mattorb/psi-action@v1
        id: psi_mobile_postpage
        with:
          url: "https://mattorb.com/level-up-shortcuts-and-the-hyper-key/"
          threshold: 80
          strategy: mobile
      - name: Running Page Speed Insights, Desktop, a typical post page
        uses: mattorb/psi-action@v1
        id: psi_desktop_postpage
        with:
          url: "https://mattorb.com/level-up-shortcuts-and-the-hyper-key/"
          threshold: 91
          strategy: desktop